language: node_js
node_js:
- '0.10'

env:
  global:
    - secure: TTxNXSIAZ/cC4fv3pnGAsUb6wnwd/egR76FPj2KP59BQC/niZw32qDLNVl36EmwOd0KZW1wgoZ2FMWkANtcdgHSqjECU4HbF9LKlZG7nf63AFdUdulmnBCMjiUmq6BxMGDWhaMY+dTEGnjgro8Qz1Y33SFHYFw9uLWLM7YPbKNU=

after_success:
  - chmod +x ./resources/update-gh-pages.sh
  - ./resources/update-gh-pages.sh
