language: node_js
node_js:
- '0.10'

env:
  global:
    - secure: gCMw/wHTBwbo9PKQMzW/DgGYa3M4iMtEWnDy8YKiBrtRyWFm66wkbJndRFIf3p4P2L4hlLoTISzBuemGTupGIWRq7urmA2C2lSL5Y05jL1Lfq+HI0zYsWZFWGVUQDLMPVxyW1fEOCZAUEfpUpd9qv4E6HsUt0CgqiBj2I0NniUQ=

after_success:
  - chmod +x ./resources/update-gh-pages.sh
  - ./resources/update-gh-pages.sh
